<?php

namespace Iapps\PaymentService\Common;

class MessageCode{

	//payment service message code start with 2XXX
    const CODE_ADD_CURRENCY_SUCCESS = 2000;
    const CODE_ADD_CURRENCY_FAILED = 2001;
    const CODE_GET_CURRENCY_SUCCESS = 2002;
    const CODE_GET_CURRENCY_FAILED = 2003;
    const CODE_EDIT_CURRENCY_SUCCESS = 2004;
    const CODE_EDIT_CURRENCY_FAILED = 2005;

    const CODE_GET_PAYMENT_MODE_SUCCESS = 2010;
    const CODE_GET_PAYMENT_MODE_FAILED = 2011;

    const CODE_ADD_COUNTRY_CURRENCY_SUCCESS = 2020;
    const CODE_ADD_COUNTRY_CURRENCY_FAILED = 2021;
    const CODE_GET_COUNTRY_CURRENCY_SUCCESS = 2022;
    const CODE_GET_COUNTRY_CURRENCY_FAILED = 2023;
    const CODE_EDIT_COUNTRY_CURRENCY_SUCCESS = 2024;
    const CODE_EDIT_COUNTRY_CURRENCY_FAILED = 2025;
    const CODE_COUNTRY_CURRENCY_INVALID_PAYMENT_MODE = 2026;
    const CODE_COUNTRY_CURRENCY_ALREADY_EXISTS = 2027;
    const CODE_COUNTRY_CURRENCY_INVALID_CURRENCY_CODE = 2028;
    const CODE_COUNTRY_CURRENCY_FAILED_VALIDATION = 2029;

    const CODE_ADD_COUNTRY_CURRENCY_PAYMENT_MODE_SUCCESS = 2030;
    const CODE_ADD_COUNTRY_CURRENCY_PAYMENT_MODE_FAILED = 2031;
    const CODE_GET_COUNTRY_CURRENCY_PAYMENT_MODE_SUCCESS = 2032;
    const CODE_GET_COUNTRY_CURRENCY_PAYMENT_MODE_FAILED = 2033;
    const CODE_EDIT_COUNTRY_CURRENCY_PAYMENT_MODE_SUCCESS = 2034;
    const CODE_EDIT_COUNTRY_CURRENCY_PAYMENT_MODE_FAILED = 2035;
    
    const CODE_RECONCILIATION_SUCCESS = 2040;
    const CODE_RECONCILIATION_FAILED = 2041;

    const CODE_GET_PAYMENT_LIST_SUCCESS = 2050 ;
    const CODE_GET_PAYMENT_LIST_FAILED = 2051 ;

    const CODE_GET_PAYMENT_REQUEST_LIST_SUCCESS = 2060 ;
    const CODE_GET_PAYMENT_REQUEST_LIST_FAILED = 2061 ;

    const CODE_PAYMENT_REQUEST_CHECK_UPDATE_SUCCESS = 2065;
    const CODE_PAYMENT_REQUEST_CHECK_UPDATE_FAIL    = 2066;
    const CODE_PAYMENT_REQUEST_CHECK_UPDATE_INVALID_STATUS  = 2070;

    //promo code

    const CODE_VALIDATE_PROMO_REWARD_FAIL  = 2080;
    const CODE_ALREADY_EXISTING_SAME_PROMO_CODE  = 2081;
    const CODE_ADD_PROMO_REWARD_SUCCESS = 2082;
    const CODE_ADD_PROMO_REWARD_FAIL  = 2083;
    const CODE_GET_PROMO_REWARD_SUCCESS = 2084;
    const CODE_GET_PROMO_REWARD_FAIL = 2085;

    const CODE_INVALID_PROMO_CODE = 2087;
    const CODE_PROMO_CODE_USED = 2089;
    const CODE_PLEASE_TRY_AGAIN_IN_1_HOURS = 2091;
    const CODE_PROMO_CODE_HAS_EXPIRED = 2093;




    const CODE_PAYMENT_REQUEST_FAIL = 2100;
    const CODE_PAYMENT_MAKE_FAIL = 2101;
    const CODE_PAYMENT_REQUEST_SUCCESS = 2102;
    const CODE_PAYMENT_MAKE_SUCCESS = 2103;
    const CODE_PAYMENT_INVALID_INFO = 2104;
    const CODE_PAYMENT_INVALID_AMOUNT = 2105;
    const CODE_TRANSACTIONID_EXISTS = 2106;
    const CODE_GET_ATTRIBUTE_SUCCESS = 2107;
    const CODE_GET_ATTRIBUTE_FAILED = 2108;
    const CODE_PAYMENT_NOT_ACCESSIBLE = 2109;
    const CODE_REQUEST_NOT_FOUND = 2110;
    const CODE_REQUEST_COMPLETED = 2111;
    const CODE_REQUEST_CANCELED = 2112;
    const CODE_INVALID_SWITCH_SETTING = 2113;
    const CODE_REQUEST_IS_ALREADY_PROCESSED = 2114;

    const CODE_PAYMENT_ATTRIBUTE_VALUE_VALIDATE_SUCCESS = 2115;
    const CODE_PAYMENT_ATTRIBUTE_VALUE_VALIDATE_FAIL = 2116;

    const CODE_PAYMENT_REQUEST_PENDING = 2117;

    const CODE_ATTRIBUTE_FOUND = 2118;
    const CODE_ATTRIBUTE_NOT_FOUND = 2119;


    const CODE_UPLOAD_RECEIPT_REFERENCE_IMAGE_SUCCESS = 2150;
    const CODE_UPLOAD_RECEIPT_REFERENCE_IMAGE_FAIL = 2151;

    const CODE_GET_AGUNG_TRANSACTION_REPORT_FAIL = 2221;
    const CODE_GET_AGUNG_TRANSACTION_REPORT_SUCCESS = 2222;

    const CODE_JOB_PROCESS_PASSED = 2223;

    //System code
    const CODE_GET_AGENT_USER_SUCCESS = 3996;

    const CODE_PAYMENT_VOIDED_SUCCESS = 2224;
    const CODE_PAYMENT_VOIDED_FAILED = 2225;
    
    const CODE_INVALID_GATEWAY_HASH_CHECKING = 2226;
    const CODE_PAYMENT_GATEWAY_TRANSACTION_REQUEST_FAILED = 2227;
    const CODE_OCBC_GATEWAY_QUERY_STATUS_FAILED = 2228;
    const OCBC_GATEWAY_TRANSACTION_VOID_STATUS_FAILED = 2229;
    const OCBC_GATEWAY_USER_CANCEL_PAYMENT_TRANSACTION = 2230;
    const OCBC_GATEWAY_ERROR = 2231;

    const CODE_CHECK_BANK_ACCOUNT_SUCCESS = 2232;
    const CODE_CHECK_BANK_ACCOUNT_FAILED = 2233;

    const CODE_CHECK_ACCOUNT_HOLDER_NAME_SUCCESS = 2234;
    const CODE_CHECK_ACCOUNT_HOLDER_NAME_FAILED = 2235;

}